#!/bin/bash

programname=$0

function usage {
    echo ""
    echo "Usage: dockergo [options]"
    echo ""
    echo "Options:"
    echo "  -k  | --kill        Kill Docker daemon"
    echo "  -s  | --start       Start Docker daemon"
    echo "  -r  | --restart     Restart Docker daemon"
    echo "  -ka | --killall     Kill all running Docker containers"
    echo "  -h                  Display help"
    echo ""
    echo "  Defaults to restart if no options are present"
    echo ""
    exit 1
}

function start_docker {
    open -a Docker; 
    DOCKER_INFO_OUTPUT="$(docker info 2> /dev/null)";

    while [[ -z ${DOCKER_INFO_OUTPUT} ]] || [[ ${DOCKER_INFO_OUTPUT} == *"ERROR"* ]]; do 
        printf "."; 
        sleep 1; 
        DOCKER_INFO_OUTPUT="$(docker info 2> /dev/null)";
    done 

    echo ""; 
    echo "Started ";
}

function kill_docker {
    osascript -e 'quit app "Docker"'; 
    echo ""; 
    echo "Killed "; 
}

function restart_docker { 
    kill_docker
    start_docker
}

function kilall_docker { 
    docker kill $(docker ps)
}

while [ "$1" != "" ]; do
    case $1 in
        -k | --kill )           shift
                                kill_docker 
                                exit      
                                ;;                       
        -s | --start )          start_docker
                                exit                              
                                ;;
        -r | --restart )        restart_docker    
                                exit
                                ;;
        -ka | --killall )       kilall_docker                                                             
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

restart_docker
